services:
  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: ${POSTGRES_USER}
    secrets:
      - postgres_password
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.3
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pg_admin_default_password
      PGADMIN_LISTEN_PORT: 80
    secrets:
      - pg_admin_default_password
    ports:
      - 8280:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    restart: unless-stopped
secrets:
  pg_admin_default_password:
    file: ./secrets/pg_admin_default_password.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
volumes:
  db:
  pgadmin:
